---

- hosts: all
  become: true
  tasks:

  - name: install updates
    apt:
      update_cache: yes
      upgrade: dist
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Upgrade CentOS
    yum:
      update_cache: yes
      name: '*'
      state: latest
    when: ansible_distribution == "CentOS"


